version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:45"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      routine-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
